import { Metadata } from "next";
import { Nunito } from "next/font/google";
import { headers } from "next/headers";
import "@/app/globals.css";
import { Navbar } from "@/components/Navbar";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const pathname = headersList.get("x-invoke-path") || "";

  const isAdminRoute = pathname.startsWith("/admin");

  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        {!isAdminRoute && <Navbar />}
        <main className={isAdminRoute ? "" : "pt-16"}>{children}</main>
      </body>
    </html>
  );
}
