import { Metadata } from "next";
import { Nunito } from "next/font/google";
import { Navbar } from "@/components/Navbar";
import "@/app/globals.css";

const nunito = Nunito({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunito.className}>
      <body>
        <Navbar />
        <main className={"pt-16"}>{children}</main>
      </body>
    </html>
  );
}
